import { Inter } from 'next/font/google'
import Navegation from '@/complements/Navegation'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Proyecto-Read_Connect 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  min-h-screen px-10`}>
        <Navegation/>
        {children}
      </body>
    </html>
  )
}
